In [251]:
import pandas as pd
import plotly.plotly as py
import plotly.tools as tls
tls.set_credentials_file(username='ducle1508', api_key='qlvxeqvivi')

# Question: "How do the countries Luther visited for J-Term distribute on the world map?"

## I used the J-Term data provided by the Center for Global Learning (dating back to 1991), count the visited time for each country and plot it on the world map using plotly.

In [235]:
df = pd.read_excel("J-Term.xlsx")

In [236]:
d = df[['Year', 'Country #1', 'Country #2', 'Country #3', 'Country #4', 'Country #5']]

In [237]:
d.columns = ['year', 'country1', 'country2', 'country3', 'country4', 'country5']
d=d.fillna('')

In [238]:
d.country1 = d.country1.apply(lambda x: x.rstrip())
d.country2 = d.country2.apply(lambda x: x.rstrip())
d.country3 = d.country3.apply(lambda x: x.rstrip())
d.country4 = d.country4.apply(lambda x: x.rstrip())
d.country5 = d.country5.apply(lambda x: x.rstrip())

In [239]:
masterlist = []
for i in ['country1', 'country2', 'country3', 'country4', 'country5']:
    for j in sorted(d[i].unique()):
        if j not in masterlist:
            masterlist.append(j)

In [240]:
ranking = []
yearlookup = []
country = []
datatable = {}

In [241]:
for x in masterlist:
    if x != '':    
        country.append(x)
        ranking.append(d[(d.country1 == x)|(d.country2 == x)|(d.country3 == x)|(d.country4 == x)|(d.country5 == x)].year.count())
        yearlookup.append(sorted(d[(d.country1 == x)|(d.country2 == x)|(d.country3 == x)|(d.country4 == x)|(d.country5 == x)].year.unique()))
datatable['Country'] = country
datatable['Ranking'] = ranking
datatable['Year'] = yearlookup

In [242]:
df = pd.DataFrame(datatable)

In [243]:
df = df.sort_values('Ranking', ascending = False).reset_index(drop=True)

In [244]:
df2 = pd.read_excel("country_code_web.xls")

In [245]:
df2

                                               Country Code
0                                          Afghanistan  AFG
1                                        Ã…land Islands  ALA
2                                              Albania  ALB
3                                              Algeria  DZA
4                                       American Samoa  ASM
5                                              Andorra  AND
6                                               Angola  AGO
7                                             Anguilla  AIA
8                                  Antigua and Barbuda  ATG
9                                            Argentina  ARG
10                                             Armenia  ARM
11                                               Aruba  ABW
12                                           Australia  AUS
13                                             Austria  AUT
14                                          Azerbaijan  AZE
15                                             Bahamas  BHS
16                                             Bahrain  BHR
17                                          Bangladesh  BGD
18                                            Barbados  BRB
19                                             Belarus  BLR
20                                             Belgium  BEL
21                                              Belize  BLZ
22                                               Benin  BEN
23                                             Bermuda  BMU
24                                              Bhutan  BTN
25                                             Bolivia  BOL
26                              Bosnia and Herzegovina  BIH
27                                            Botswana  BWA
28                                              Brazil  BRA
29                              British Virgin Islands  VGB
..                                                 ...  ...
208          The former Yugoslav Republic of Macedonia  MKD
209                                        Timor-Leste  TLS
210                                               Togo  TGO
211                                            Tokelau  TKL
212                                              Tonga  TON
213                                Trinidad and Tobago  TTO
214                                            Tunisia  TUN
215                                             Turkey  TUR
216                                       Turkmenistan  TKM
217                           Turks and Caicos Islands  TCA
218                                             Tuvalu  TUV
219                                             Uganda  UGA
220                                            Ukraine  UKR
221                               United Arab Emirates  ARE
222  United Kingdom of Great Britain and Northern I...  GBR
223                                           Tanzania  TZA
224                                              U.S.A  USA
225                                     Virgin Islands  VIR
226                                            Uruguay  URY
227                                         Uzbekistan  UZB
228                                            Vanuatu  VUT
229                 Venezuela (Bolivarian Republic of)  VEN
230                                            Vietnam  VNM
231                          Wallis and Futuna Islands  WLF
232                                     Western Sahara  ESH
233                                              Yemen  YEM
234                                             Zambia  ZMB
235                                           Zimbabwe  ZWE
236                                                NaN  NaN
237  * ISO ALPHA-3 codes (ISO 3166-1 alpha-3 codes)...  NaN

[238 rows x 2 columns]

In [246]:
def matchcountrycode(country):
    if country in ['England', 'Scotland', 'Northern Ireland']:
        return 'GBR'
    elif country == 'Leeward Islands':
        return 'NLD'
    elif country == 'Canary Islands': 
        return 'ESP'
    else:
        if df2[df2['Country'] == country].Code.get_values().size == 0:
            return ''
        else:
            return df2[df2['Country'] == country].Code.get_values()[0]

In [247]:
df['Code'] = df.Country.apply(lambda x: matchcountrycode(x))
df['Year'] = df['Year'].apply(lambda x: str(x)[1:-1])
df['Text'] = df['Country'] + '<br>' + "Visited in " + df['Year']

In [248]:
df

,Country,Ranking,Year,Code,Text
0,England,64,"1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998...",GBR,"England<br>Visited in 1991, 1992, 1993, 1994, ..."
1,U.S.A,57,"1993, 1995, 2001, 2002, 2003, 2004, 2005, 2006...",USA,"U.S.A<br>Visited in 1993, 1995, 2001, 2002, 20..."
2,Germany,38,"1991, 1993, 1994, 1996, 1997, 1999, 2000, 2001...",DEU,"Germany<br>Visited in 1991, 1993, 1994, 1996, ..."
3,France,28,"1991, 1993, 1996, 1999, 2000, 2001, 2003, 2004...",FRA,"France<br>Visited in 1991, 1993, 1996, 1999, 2..."
4,Italy,23,"1991, 1999, 2000, 2001, 2002, 2003, 2005, 2007...",ITA,"Italy<br>Visited in 1991, 1999, 2000, 2001, 20..."
5,Czech Republic,21,"1991, 1992, 1996, 1997, 1998, 1999, 2000, 2001...",CZE,"Czech Republic<br>Visited in 1991, 1992, 1996,..."
6,Ireland,20,"1996, 1998, 1999, 2001, 2002, 2004, 2005, 2006...",IRL,"Ireland<br>Visited in 1996, 1998, 1999, 2001, ..."
7,Bahamas,20,"1991, 1992, 1993, 1994, 1995, 1996, 2001, 2002...",BHS,"Bahamas<br>Visited in 1991, 1992, 1993, 1994, ..."
8,Austria,18,"1991, 1994, 1996, 1998, 1999, 2003, 2007, 2008...",AUT,"Austria<br>Visited in 1991, 1994, 1996, 1998, ..."
9,South Africa,18,"1998, 2000, 2001, 2003, 2005, 2006, 2007, 2008...",ZAF,"South Africa<br>Visited in 1998, 2000, 2001, 2..."
10,Japan,18,"1991, 1992, 1993, 1994, 1995, 1997, 1998, 2000...",JPN,"Japan<br>Visited in 1991, 1992, 1993, 1994, 19..."
11,China,17,"1991, 1992, 1997, 1999, 2003, 2004, 2005, 2006...",CHN,"China<br>Visited in 1991, 1992, 1997, 1999, 20..."
12,Russia,17,"1991, 1992, 1994, 1995, 1996, 1997, 1998, 1999...",RUS,"Russia<br>Visited in 1991, 1992, 1994, 1995, 1..."
13,Poland,17,"1991, 1992, 1994, 1996, 1997, 1999, 2000, 2001...",POL,"Poland<br>Visited in 1991, 1992, 1994, 1996, 1..."
14,Tanzania,15,"2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011...",TZA,"Tanzania<br>Visited in 2004, 2005, 2006, 2007,..."
15,Spain,15,"1991, 1992, 1994, 1995, 1997, 2000, 2002, 2003...",ESP,"Spain<br>Visited in 1991, 1992, 1994, 1995, 19..."
16,Norway,15,"1991, 1993, 1996, 1997, 2002, 2004, 2008, 2009...",NOR,"Norway<br>Visited in 1991, 1993, 1996, 1997, 2..."
17,New Zealand,14,"1993, 1995, 2001, 2002, 2003, 2004, 2005, 2007...",NZL,"New Zealand<br>Visited in 1993, 1995, 2001, 20..."
18,Ecuador,14,"2000, 2004, 2007, 2009, 2010, 2012, 2013, 2015...",ECU,"Ecuador<br>Visited in 2000, 2004, 2007, 2009, ..."
19,Peru,14,"1996, 1997, 1998, 2001, 2002, 2003, 2005, 2007...",PER,"Peru<br>Visited in 1996, 1997, 1998, 2001, 200..."
20,Greece,14,"1993, 1994, 1996, 1997, 1998, 2003, 2005, 2007...",GRC,"Greece<br>Visited in 1993, 1994, 1996, 1997, 1..."
21,Canary Islands,12,"1997, 1998, 2000, 2002, 2004, 2005, 2006, 2007...",ESP,"Canary Islands<br>Visited in 1997, 1998, 2000,..."
22,Brazil,12,"1997, 1999, 2000, 2004, 2005, 2006, 2007, 2008...",BRA,"Brazil<br>Visited in 1997, 1999, 2000, 2004, 2..."
23,Jamaica,10,"1992, 1994, 1995, 2006, 2007, 2009, 2011, 2013...",JAM,"Jamaica<br>Visited in 1992, 1994, 1995, 2006, ..."
24,Mexico,10,"1991, 1993, 2001, 2004, 2005, 2006, 2007, 2009",MEX,"Mexico<br>Visited in 1991, 1993, 2001, 2004, 2..."
25,Hong Kong,8,"1991, 1992, 1997, 1999, 2001, 2015, 2016",HKG,"Hong Kong<br>Visited in 1991, 1992, 1997, 1999..."
26,Australia,8,"1999, 2001, 2004, 2005, 2006, 2008, 2009",AUS,"Australia<br>Visited in 1999, 2001, 2004, 2005..."
27,Ghana,8,"1999, 2000, 2004, 2006, 2008, 2012, 2017",GHA,"Ghana<br>Visited in 1999, 2000, 2004, 2006, 20..."
28,Chile,8,"1996, 1997, 1998, 2005, 2006, 2008, 2012, 2015",CHL,"Chile<br>Visited in 1996, 1997, 1998, 2005, 20..."
29,Guatemala,7,"1997, 1998, 1999, 2001, 2002, 2008, 2017",GTM,"Guatemala<br>Visited in 1997, 1998, 1999, 2001..."
...,...,...,...,...,...
46,Slovakia,4,"1996, 1997, 1999",SVK,"Slovakia<br>Visited in 1996, 1997, 1999"
47,Estonia,3,"1999, 2002, 2003",EST,"Estonia<br>Visited in 1999, 2002, 2003"
48,Argentina,3,"2008, 2010, 2012",ARG,"Argentina<br>Visited in 2008, 2010, 2012"
49,Nicaragua,3,"2004, 2006, 2011",NIC,"Nicaragua<br>Visited in 2004, 2006, 2011"
50,Namibia,3,"2006, 2010, 2014",NAM,"Namibia<br>Visited in 2006, 2010, 2014"
51,Egypt,3,"1991, 2009, 2010",EGY,"Egypt<br>Visited in 1991, 2009, 2010"
52,Belize,3,"2015, 2016, 2017",BLZ,"Belize<br>Visited in 2015, 2016, 2017"
53,Costa Rica,3,"1995, 2009, 2017",CRI,"Costa Rica<br>Visited in 1995, 2009, 2017"
54,Cambodia,3,"2014, 2015, 2017",KHM,"Cambodia<br>Visited in 2014, 2015, 2017"
55,Cuba,2,"2014, 2016",CUB,"Cuba<br>Visited in 2014, 2016"
56,Thailand,2,"1995, 1996",THA,"Thailand<br>Visited in 1995, 1996"
57,Bolivia,2,"2009, 2011",BOL,"Bolivia<br>Visited in 2009, 2011"
58,Jordan,2,"2012, 2014",JOR,"Jordan<br>Visited in 2012, 2014"
59,Singapore,1,2005,SGP,Singapore<br>Visited in 2005
60,Botswana,1,2004,BWA,Botswana<br>Visited in 2004
61,Iceland,1,2009,ISL,Iceland<br>Visited in 2009
62,Guyana,1,2011,GUY,Guyana<br>Visited in 2011
63,Ukraine,1,1994,UKR,Ukraine<br>Visited in 1994
64,Leeward Islands,1,2014,NLD,Leeward Islands<br>Visited in 2014
65,Cook Islands,1,2005,COK,Cook Islands<br>Visited in 2005
66,Honduras,1,1997,HND,Honduras<br>Visited in 1997
67,Haiti,1,2016,HTI,Haiti<br>Visited in 2016
68,South Korea,1,2003,KOR,South Korea<br>Visited in 2003
69,Bosnia and Herzegovina,1,2014,BIH,Bosnia and Herzegovina<br>Visited in 2014
70,Vietnam,1,2016,VNM,Vietnam<br>Visited in 2016
71,United Arab Emirates,1,2009,ARE,United Arab Emirates<br>Visited in 2009
72,El Salvador,1,2004,SLV,El Salvador<br>Visited in 2004
73,Sri Lanka,1,1996,LKA,Sri Lanka<br>Visited in 1996
74,Niger,1,1999,NER,Niger<br>Visited in 1999
75,Serbia,1,2014,SRB,Serbia<br>Visited in 2014

In [255]:
data = [ dict(
        type = 'choropleth',
        locations = df['Code'],
        z = df['Ranking'],
        text = df['Text'],
        colorscale = [[0,"rgb(5, 10, 172)"],[0.35,"rgb(40, 60, 190)"],[0.5,"rgb(70, 100, 245)"],\
            [0.6,"rgb(90, 120, 245)"],[0.7,"rgb(106, 137, 247)"],[1,"rgb(220, 220, 220)"]],
        autocolorscale = False,
        reversescale = True,
        marker = dict(
            line = dict (
                color = 'rgb(180,180,180)',
                width = 0.5
            ) ),
        colorbar = dict(
            autotick = False,
            tickprefix = '',
            title = 'Visited times'),
      ) ]

layout = dict(
    title = 'J-Term Countries',
    geo = dict(
        showframe = False,
        showcoastlines = False,
        projection = dict(
            type = 'Miller'
        )
    )
)

fig = dict( data=data, layout=layout )
py.iplot( fig, validate=False, filename='d3-world-map' )

High five! You successfuly sent some data to your account on plotly. View your plot in your browser at https://plot.ly/~ducle1508/0 or inside your plot.ly account where it is named 'd3-world-map'